services:
 
  mock-instance:
    build: . 
    network_mode: "host"
    environment:
      - RABBIT_USER
      - RABBIT_PASS
      - RABBIT_HOST
      - RABBIT_PORT
      - RABBIT_PUBLISH_QUEUE
      - RABBIT_CONSUME_QUEUE
      - INTERVAL
      - IS_INSTANCE
      - HOST
      - NODE_PORT
      - HEALTH
    healthcheck:
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 5s
