#!/usr/bin/env sh

{
    echo "RABBIT_USER=$RABBIT_USER"
    echo "RABBIT_PASS=$RABBIT_PASS"
    echo "RABBIT_HOST=$RABBIT_HOST"
    echo "RABBIT_PORT=$RABBIT_PORT"
    echo "INTERVAL=$INTERVAL"
    echo "SCHEMA_PATH=$SCHEMA_PATH"
    echo "RABBIT_QUEUE=$RABBIT_QUEUE"
    echo "NODE_PORT=$NODE_PORT"

    echo "LOGGING_LEVEL=$LOGGING_LEVEL"
} > .env
